source/Loyalty_Program_App/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("clientapi.urls")),
]

urlpatterns += i18n_patterns(
    path('', include('merchantapp.urls')),
    path('accounts/', include("accounts.urls")),
    path('web/', include('webapp.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts import views as accounts_views

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", accounts_views.UserDetailsView.as_view(), name="profile"),
    path("<int:pk>/edit/", accounts_views.UserUpdateView.as_view(), name="edit_profile"),
    path("<int:pk>/change-password/", accounts_views.ChangePasswordView.as_view(), name="change_password")
]

source/webapp/urls.py
from django.urls import path
from webapp import views

app_name = 'webapp'

urlpatterns = [
    path('', views.index_view, name='index'),
]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def _create_user(self, phone, password=None, **extra_fields):
        if not phone:
            raise ValueError(_('TheGivenPhoneMustBeSet'))
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(phone, password, **extra_fields)

    def create_superuser(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    phone_regex = RegexValidator(regex=r'^7?\d{10}',
                                 message=_("PhoneValidatorMessage"))
    phone = models.CharField(validators=[phone_regex], max_length=12, unique=True, verbose_name=_("PhoneNumber"),
                             blank=False, help_text=_("HelpTextPhone"))
    tg_id = models.IntegerField(null=True, blank=True, unique=True, verbose_name=_("TelegramID"))
    birth_date = models.DateField(null=True, blank=True, verbose_name=_("DateOfBirth"))
    name = models.CharField(null=True, blank=True, max_length=100, verbose_name=_("Name"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("Email"))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

source/accounts/forms.py
from django import forms
from django.forms import widgets
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm


class UserAdminCreationForm(UserCreationForm):
    class Meta:
        model = get_user_model()
        fields = ['phone', 'name', 'birth_date', 'email']
        widgets = {
            "birth_date": forms.DateInput(attrs={'class': 'form-control', 'placeholder': 'Select a date', 'type': 'date'}),
        }


class UserChangeForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = ["name", "email"]
        label = {"name": "Name", "email": "Email"}


class PasswordChangeForm(forms.ModelForm):
    old_password = forms.CharField(label="Old password", strip=False, widget=forms.PasswordInput)
    password = forms.CharField(label="New password", strip=False, widget=forms.PasswordInput)
    password_confirm = forms.CharField(label="Confirm password", strip=False, widget=forms.PasswordInput)

    def clean_password_confirm(self):
        password = self.cleaned_data["password"]
        password_confirm = self.cleaned_data["password_confirm"]
        if password and password_confirm and password != password_confirm:
            raise forms.ValidationError("Passwords are not equal")
        return password_confirm

    def clean_old_password(self):
        old_password = self.cleaned_data["old_password"]
        if not self.instance.check_password(old_password):
            raise forms.ValidationError("Wrong old password")
        return old_password

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

    class Meta:
        model = get_user_model()
        fields = ["old_password", "password", "password_confirm"]

source/accounts/views.py
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, CreateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth import get_user_model, update_session_auth_hash

from accounts.forms import PasswordChangeForm, UserChangeForm

from django.shortcuts import render, redirect
from accounts.forms import UserAdminCreationForm


class RegisterView(CreateView):
    model = get_user_model()
    template_name = 'registration/register.html'
    form_class = UserAdminCreationForm
    success_url = 'accounts:login'


class UserDetailsView(LoginRequiredMixin, DetailView):
    model = get_user_model()
    template_name = "user_detail.html"
    context_object_name = "user_object"


class ChangeProfileAccessMixin(UserPassesTestMixin):
    def test_func(self):
        return self.request.user == self.get_object() or self.request.user.is_superuser or\
               self.request.user.groups.filter(name="admins")


class UserUpdateView(ChangeProfileAccessMixin, UpdateView):
    model = get_user_model()
    form_class = UserChangeForm
    template_name = "edit_profile.html"
    context_object_name = "user_object"

    def get_success_url(self):
        return reverse("accounts:profile", kwargs={"pk": self.object.pk})


class ChangePasswordView(ChangeProfileAccessMixin, UpdateView):
    model = get_user_model()
    form_class = PasswordChangeForm
    template_name = "change_password.html"
    context_object_name = "user_object"

    def form_valid(self, form):
        form.save()
        update_session_auth_hash(self.request, form.instance)
        return redirect("accounts:profile", pk=self.get_object().pk)

source/accounts/templates/change_password.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "ChangingPasswordTitle" %}{% endblock %}

{% block content %}

    <h1 class="text-center my-5">{% trans "ChangePassword" %} <i>{{ user_object.phone }}</i></h1>

    <form action="{% url "accounts:change_password" user_object.pk %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success" style="width: 100%">{% trans "ChangeButton" %}</button>
    </form>

{% endblock %}

source/accounts/templates/edit_profile.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "EditingTitle" %} {{ user_object.username }}{% endblock %}

{% block content %}

    <h1 class="text-center">{% trans "EditProfile" %}</h1>

    <form action="{% url "accounts:edit_profile" user_object.pk %}" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-success" style="width: 100%">{% trans "EditButton" %}</button>
    </form>

{% endblock %}

source/accounts/templates/user_detail.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% trans "User" %} {{ user_object.username }}{% endblock %}

{% block content %}

    <div class="text-center">
        <h1>{% trans "Profile" %}</h1>
        {% ifequal user user_object %}
            <p><a class="text-decoration-none" href="{% url "accounts:edit_profile" user_object.pk %}">{% trans "EditProfileLink" %}</a></p>
            <p><a class="text-decoration-none" href="{% url "accounts:change_password" user_object.pk %}">{% trans "ChangePasswordLink" %}</a></p>
        {% endifequal %}
        <p><b>{% blocktrans %}User's phone number: {% endblocktrans %}</b>{{ user_object.phone }}</p>
        {% if user_object.first_name %}
            <p><b>{% trans "Name" %}: </b>{{ user_object.first_name }}</p>
        {% endif %}
    </div>

{% endblock %}