source/Loyalty_Program_App/urls.py
from django.conf.urls.i18n import i18n_patterns
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include("clientapi.urls")),
]

urlpatterns += i18n_patterns(
    path('', include('merchantapp.urls')),
    path('accounts/', include("accounts.urls")),
    path('web/', include('webapp.urls'))
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/accounts/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path
from accounts import views as accounts_views

app_name = 'accounts'

urlpatterns = [
    path("login/", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("create/", accounts_views.RegisterView.as_view(), name="register"),
    path("<int:pk>/", accounts_views.UserDetailsView.as_view(), name="profile"),
    path("<int:pk>/edit/", accounts_views.UserUpdateView.as_view(), name="edit_profile"),
    path("<int:pk>/change-password/", accounts_views.ChangePasswordView.as_view(), name="change_password")
]

source/merchantapp/urls.py
from django.urls import path
from merchantapp import views as merchant_views

app_name = 'merchantapp'

urlpatterns = [
    path('', merchant_views.MerchantIndexView.as_view(), name='merchant_index'),
    path('s/', merchant_views.CustomerSearchView.as_view(), name='user_search'),
    path('customers/', merchant_views.CustomerListView.as_view(), name='customers'),
    path('customers/download/', merchant_views.download_customers_file, name='customers_download'),
    path('programs/', merchant_views.ProgramListView.as_view(), name='programs'),
    path('programs/create/', merchant_views.ProgramCreateView.as_view(), name='program_create'),
    path('programs/<int:pk>/update/', merchant_views.ProgramUpdateView.as_view(), name='program_update'),
    path('branches/', merchant_views.BranchListView.as_view(), name='branches'),
    path('branches/create/', merchant_views.BranchCreateView.as_view(), name='branch_create'),
    path('branches/<int:pk>/update/', merchant_views.BranchUpdateView.as_view(), name='branch_update'),
    path('orders/<int:pk>/', merchant_views.OrderProcessingView.as_view(), name='orders'),
    path('orders/create/', merchant_views.OrderCreateView.as_view(), name='order_create'),
    path('employees/', merchant_views.EmployeeListView.as_view(), name='employees_list'),
    path('employee/<int:pk>/', merchant_views.EmployeeDetailsView.as_view(), name='employee_details'),
    path('employee/<int:pk>/expel/', merchant_views.EmployeeDeleteView.as_view(), name='employee_expel'),
]

source/webapp/urls.py
from django.urls import path
from webapp import views

app_name = 'webapp'

urlpatterns = [
    path('', views.index_view, name='index'),
]

source/accounts/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import gettext_lazy as _


class CustomUserManager(BaseUserManager):
    def _create_user(self, phone, password=None, **extra_fields):
        if not phone:
            raise ValueError(_('TheGivenPhoneMustBeSet'))
        user = self.model(phone=phone, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(phone, password, **extra_fields)

    def create_superuser(self, phone, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(phone, password, **extra_fields)


class CustomUser(AbstractUser):
    username = None
    phone_regex = RegexValidator(regex=r'^7?\d{10}',
                                 message=_("PhoneValidatorMessage"))
    phone = models.CharField(validators=[phone_regex], max_length=12, unique=True, verbose_name=_("PhoneNumber"),
                             blank=False, help_text=_("HelpTextPhone"))
    tg_id = models.IntegerField(null=True, blank=True, unique=True, verbose_name=_("TelegramID"))
    birth_date = models.DateField(null=True, blank=True, verbose_name=_("DateOfBirth"))
    name = models.CharField(null=True, blank=True, max_length=100, verbose_name=_("Name"))
    email = models.EmailField(null=True, blank=True, verbose_name=_("Email"))

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'phone'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

source/merchantapp/models.py
from django.contrib.auth import get_user_model
from django.db import models, transaction
from django.utils.translation import gettext_lazy as _


status_choices = [
    ('RETURNED', _('Returned')),
    ('FINISHED', _('Finished'))
]
merchant_categories = [
    ('CATERING', _('Catering')),
    ('CAR', _('Car'))
]


class BaseModel(models.Model):
    time_created = models.DateTimeField(auto_now_add=True, verbose_name=_('TimeCreated'))
    time_updated = models.DateTimeField(auto_now=True, verbose_name=_('TimeUpdated'))
    active = models.BooleanField(default=True, verbose_name=_('Active'))

    class Meta:
        abstract = True


class Merchant(BaseModel):
    code = models.CharField(max_length=150, unique=True, verbose_name=_('Identifier'))
    name = models.CharField(max_length=150, verbose_name=_('Title'))
    director = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                                 related_name='merchant_director', verbose_name=_('Supervisor'))
    employees = models.ManyToManyField(get_user_model(), related_name='merchants', verbose_name=_('Employees'))
    category = models.CharField(choices=merchant_categories, max_length=20, verbose_name=_('Category'))

    def __str__(self):
        return f'{self.name}'


class Branch(BaseModel):
    code = models.CharField(max_length=150, unique=True, verbose_name=_('Identifier'))
    name = models.CharField(max_length=150, verbose_name=_('Title'))
    merchant = models.ForeignKey('Merchant', on_delete=models.CASCADE, related_name='merchant', verbose_name=_('Partner'))
    address = models.ForeignKey('Address', on_delete=models.CASCADE, related_name='address', verbose_name='Адрес')
    description = models.TextField(max_length=1000, blank=True, null=True, verbose_name=_('Description'))

    def __str__(self):
        return f'{self.name}'


class Address(BaseModel):
    street = models.CharField(max_length=150, verbose_name=_('Street'))
    building = models.CharField(max_length=20, verbose_name=_('Building'))
    apartment = models.CharField(max_length=20, blank=True, null=True, verbose_name=_('Office'))
    city = models.CharField(max_length=50, verbose_name=_('City'))
    link2gis = models.URLField(verbose_name=_('LinkTo2GIS'))
    latitude = models.DecimalField(max_digits=9, decimal_places=6, verbose_name=_('Latitude'))
    longitude = models.DecimalField(max_digits=9, decimal_places=6, verbose_name=_('Longitude'))

    def __str__(self):
        return f'{self.street}'


class Program(BaseModel):
    code = models.CharField(max_length=150, unique=True, verbose_name=_('Identifier'))
    title = models.CharField(max_length=150, verbose_name=_('Title'))
    condition = models.ForeignKey('ProgramCondition', on_delete=models.CASCADE,
                                  related_name='condition', verbose_name=_('Condition'))
    reward = models.ForeignKey('ProgramReward', on_delete=models.CASCADE, related_name='reward', verbose_name=_('Reward'))
    branch = models.ManyToManyField('Branch', related_name='branch', verbose_name=_('Branch'))
    start_date = models.DateTimeField(blank=True, null=True, verbose_name=_('StartDate'))
    end_date = models.DateTimeField(blank=True, null=True, verbose_name=_('EndDate'))
    description = models.TextField(max_length=1000, verbose_name=_('Description'))

    def __str__(self):
        return self.title


class ProgramReward(BaseModel):
    reward_type = models.ForeignKey('ProgramRewardType', on_delete=models.CASCADE,
                                    related_name='type', verbose_name=_('RewardType'))
    amount = models.PositiveIntegerField(default=0, verbose_name=_('Amount'))

    def __str__(self):
        return f"{str(self.reward_type)} x {self.amount}"


class ProgramRewardType(BaseModel):
    code = models.CharField(max_length=50, verbose_name=_('Identifier'))
    title = models.CharField(max_length=150, verbose_name=_('Title'))

    def __str__(self):
        return self.title


class ProgramCondition(BaseModel):
    condition_type = models.ForeignKey('ProgramConditionType', on_delete=models.CASCADE,
                                       related_name='type', verbose_name=_('ConditionType'))
    amount = models.PositiveIntegerField(default=0, verbose_name=_('Amount'))

    def __str__(self):
        return f"{str(self.condition_type)} x {self.amount}"


class ProgramConditionType(BaseModel):
    code = models.CharField(max_length=50, verbose_name=_('Identifier'))
    title = models.CharField(max_length=150, verbose_name=_('Title'))

    def __str__(self):
        return self.title


class Order(BaseModel):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='order_user', verbose_name=_('User'))
    status = models.CharField(choices=status_choices, max_length=50, verbose_name=_('Status'))
    completion_date = models.DateTimeField(verbose_name=_('EndDate'))
    amount = models.PositiveIntegerField(verbose_name=_('Amount'))
    price = models.PositiveIntegerField(verbose_name=_('Price'))
    program = models.ForeignKey('Program', on_delete=models.CASCADE,
                                related_name='order_program', verbose_name=_('Program'))

    def __str__(self):
        return f'{self.pk} - {self.user}'


class UserReward(BaseModel):
    user = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                             related_name='user_reward', verbose_name=_('User'))
    program = models.ForeignKey('Program', on_delete=models.CASCADE,
                                related_name='reward_program', verbose_name=_('Program'))
    expire_date = models.DateTimeField(blank=True, null=True, verbose_name=_('ExpireDate'))
    redeemed = models.BooleanField(default=False, verbose_name=_('Redeemed'))

    def __str__(self):
        return f'{self.user} - {self.program.reward}'


class Article(BaseModel):
    title = models.CharField(max_length=150, verbose_name=_('TitleZ'))
    text = models.TextField(max_length=2000, verbose_name=_('Text'))
    author = models.ForeignKey(get_user_model(), on_delete=models.CASCADE,
                               related_name='article_author', verbose_name=_('Author'))

    def __str__(self):
        return f'{self.title} - {self.author}'

source/merchantapp/forms.py
from django import forms

from merchantapp.models import Program, ProgramCondition, ProgramConditionType, ProgramReward, ProgramRewardType,\
    Branch, Address


class UserSearchForm(forms.Form):
    id = forms.CharField(max_length=150, required=False, label='Search')


class ProgramForm(forms.ModelForm):
    condition = forms.IntegerField(min_value=0, label='Требуется покупок')
    reward = forms.IntegerField(min_value=0, label='Будет начислено наград')

    def clean(self):
        cleaned_data = super().clean()

        default_program_condition_type = 'number_of_purchases'
        condition_type = ProgramConditionType.objects.get(code__exact=default_program_condition_type)
        condition = ProgramCondition.objects.get_or_create(condition_type=condition_type,
                                                           amount=cleaned_data['condition'])
        default_program_reward_type = 'free_product'
        reward_type = ProgramRewardType.objects.get(code__exact=default_program_reward_type)
        reward = ProgramReward.objects.get_or_create(reward_type=reward_type,
                                                     amount=cleaned_data['reward'])

        cleaned_data['condition'] = condition[0]
        cleaned_data['reward'] = reward[0]

        return cleaned_data

    class Meta:
        model = Program
        fields = ['code', 'title', 'condition', 'reward', 'branch', 'description', 'active']


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        exclude = ['active']


class BranchForm(forms.ModelForm):
    class Meta:
        model = Branch
        fields = ['code', 'name', 'merchant', 'description', 'active']

source/merchantapp/templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="{% static "css/main.css" %}">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
            crossorigin="anonymous" defer></script>
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>Document</title>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container">
        <a class="navbar-brand" href="{% url 'merchantapp:merchant_index' %}">{% trans "MainLink" %}</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                {% if  user.is_authenticated %}
                    <li class="nav-item">
                    {% if request.user.is_superuser or request.user.groups == 'staff' or request.user.groups == 'merchant-manager' or request.user.groups == 'merchant-employee' %}
                        <a class="nav-link" href="{% url 'merchantapp:programs' %}">{% trans "ProgramsLink" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'merchantapp:branches' %}">{% trans "BranchLink" %}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'merchantapp:employees_list' %}">Employees</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'merchantapp:customers' %}">{% trans "Clients" %}</a>
                    </li>
                        {% endif %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:logout' %}">{% trans "Logout" %}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'accounts:login' %}">{% trans "Login" %}</a>
                    </li>
                {% endif %}
                <li class="nav-item dropdown">
                    {% get_current_language as LANGUAGE_CODE %}
                    {% get_available_languages as LANGUAGES %}
                    {% get_language_info_list for LANGUAGES as languages %}
                    {% get_language_info for LANGUAGE_CODE as current_language %}
                    <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown">
                        {{ current_language.name_local }}
                    </a>
                    <div class="dropdown-menu">
                        {% for language in languages %}
                            <a href="/{{ language.code }}{{ language_base_link }}" class="dropdown-item">
                                {{ language.name_local }}({{ language.code }})
                            </a>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>
<div class="container mt-4">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

source/merchantapp/templates/index.html
{% extends 'base.html' %}
{% load i18n %}
{% load merchant_tags %}
{% block content %}
    <form method="get" action={% url 'merchantapp:user_search' %}>
        <div class="input-group">
             {% if request.user.is_superuser or request.user.groups == 'Stuff' or request.user.groups == 'Merch-man' or request.user.groups == 'Merch-emp' %}
            <input class="form-control border" type="search" name="id" placeholder="Search">
            <button class="btn btn-secondary" type="submit">{% trans "Search" %}</button>
            {% endif %}
        </div>
    </form>
    {% if customuser_list %}
        {% for user in customuser_list.all %}
            <div class="card mt-3" style="width: 30rem;">
                <div class="card-body">
                    <h5 class="card-title">{{ user }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted">{{ user.first_name }} {{ user.last_name }}</h6>
                    <p class="card-text">{% blocktrans %}Available awards:{% endblocktrans %} {{ user.user_reward.all|redeemable_count }}</p>
                    {% for reward in user.user_reward.all %}
                        {{ reward.get_redeemable }}
                        {% endfor %}
                    <p class="card-text">{% blocktrans %}Completed Orders:{% endblocktrans %} {{ user.order_user.count }}</p>
                    <a class="btn btn-sm btn-secondary me-2 {% if user.user_reward.all|redeemable_count == 0 %}disabled{% endif %}"
                       href="{% url 'merchantapp:redeem_user_reward' user.pk %}">{% blocktrans %}Issue a reward{% endblocktrans %}</a>
                    <a class="btn btn-sm btn-secondary me-2" href="{% url 'merchantapp:order_create' %}?customer={{ user.pk }}">{% trans "Checkout" %}</a>
                    <a class="btn btn-sm btn-secondary" href="{% url 'merchantapp:orders' user.pk %}">{% blocktrans %}Purchase history{% endblocktrans %}</a>
                </div>
            </div>
        {% endfor %}
    {% endif %}
{% endblock %}

source/merchantapp/templates/program.html
{% extends 'base.html' %}
{% load i18n %}
{% block content %}
    <h1>{% trans "Programs" %}</h1>
    <a href="{% url 'merchantapp:program_create' %}">{% blocktrans %}Add program{% endblocktrans %}</a>
    <table class="table table-hover">
        <thead>
        <tr>
            <th scope="col" style="width: 5%">#</th>
            <th scope="col" style="width: 10%">{% trans "Title" %}</th>
            <th scope="col" style="width: 10%">{% trans "Condition" %}</th>
            <th scope="col" style="width: 10%">{% trans "Reward" %}</th>
            <th scope="col" style="width: 20%">{% trans "Description" %}</th>
            <th scope="col" style="width: 5%">{% trans "Actions" %}</th>
        </tr>
        </thead>
        <tbody>
        {% for program in program_list.all %}
            <tr>
                <th scope="row">{{ program.id }}</th>
                <td>{{ program.title }}</td>
                <td>{{ program.condition }}</td>
                <td>{{ program.reward }}</td>
                <td>{{ program.description }}</td>
                    <td><a href="{% url 'merchantapp:program_update' program.pk %}">{% trans "Refresh" %}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

source/merchantapp/templates/program_create.html
{% extends 'base.html' %}
{% block content %}
    <form class="w-50" action="{% url 'merchantapp:program_create' %}" method="post" novalidate>
        {% include 'partial/form.html' with button_text='Отправить' %}
    </form>
{% endblock %}

source/merchantapp/templates/program_update.html
{% extends 'base.html' %}
{% block content %}
    <form class="w-50" method="post" novalidate>
        {% include 'partial/form.html' with button_text='Отправить' %}
    </form>
{% endblock %}